# Tipos de Datos

Existen diferentes tipos de datos en Python. Los tipos de datos estandar con los que cuenta son:
<pre>
    Numeros (enteros, flotantes,long, complejos )
    Bool
    Cadenas de texto
    Sequencias(listas,tuplas y diccionarios)
    NoneType

La declaración de una variable se hace de la siguiente forma:

In [1]:
a=17 #numero entero
b=0.5 #punto flotante
c=4+5j #numero complejo

asignación múltiple:

In [2]:
d,e,f,g,h,i=5,.6,"hola", None,5j,True #Los strings se escriben con comillas simples o dobles

Para saber el tipo de datos usar type()

In [3]:
print(type(d),type(e),type(f),type(g),type(h),type(i))

<class 'int'> <class 'float'> <class 'str'> <class 'NoneType'> <class 'complex'> <class 'bool'>


si operamos sobre tipos numéricos, python promocionará los tipos con menor información al de mayor información

In [4]:
4+5.5+3j

(9.5+3j)

Para concatenar strings usamos el signo +

In [5]:
"hola " + "mundo"

'hola mundo'

Un error sería realizar la siguiente operación: "hola"+5. Pero sí nos permite realizar "hola"*5

In [6]:
"hola"*5

'holaholaholaholahola'

## Listas y Tuplas

Un ejemplo de lista sería la lista de estudiantes de un salón, vemos que cada uno de los estudiantes tiene nombre, apellido, sexo, edad, entre otros. Entonces una lista viene a ser información dispuesta de manera ordenada, puede ser 0,1, ... registros; y ésta información puede ser de diferentes tipos.

Una tupla es similar a una lista pero la información no puede ser cambiada, esto es útil cuando pensamos por ejemplo en las coordenadas geográficas de un lugar en específico, o cuando apuntamos a una dirección de memoria. Por lo cual pensamos en tuplas cuando queremos proteger un script de sufrir cambios. 

Las listas son estructuras mutables, mientras que las tuplas no. Es decir en las listas podemos añadir elementos, retirar, reordenar, cambiar el valor de un elemento, etc. Mientras que en las no podemos realizar estas operaciones. Esto hace que el procesar tuplas sea más rápido que el procesar listas.

In [7]:
s=[1, "hola" , 3.5]
t=(1, "hola" , 3.5)
t

(1, 'hola', 3.5)

In [8]:
print(type(s))
print(type(t))

<class 'list'>
<class 'tuple'>


Cuando queremos transformar una lista en tupla usamos __tuple()__ y para el efecto contrario usamos __list()__

In [9]:
s1=tuple(s)
t1=list(t)
print(type(s1))
print(type(t1))

<class 'tuple'>
<class 'list'>


## Diccionarios

En las listas y tuplas, teníamos una cosa en común: los items eran ordenados, comenzaban en el índice 0, e iban de uno en uno. Es decir, son tipos de datos ordenados. Los diccionarios son del tipo desordenado, pues no son numerados por índice. 
En lugar de índice, tenemos llaves

In [10]:
x = {'Sandra Martinez': 'sandra95@unmsm.edu.pe', 'Julio Diaz': 'julio2@hotmail.com'}
x['Sandra Martinez'] # Retrieve a value by using the indexing operator

'sandra95@unmsm.edu.pe'

In [11]:
x['Ana Dominguez'] = None
x['Ana Dominguez']

In [12]:
x

{'Sandra Martinez': 'sandra95@unmsm.edu.pe',
 'Julio Diaz': 'julio2@hotmail.com',
 'Ana Dominguez': None}

In [13]:
for nombre in x:
    print(x[nombre])

sandra95@unmsm.edu.pe
julio2@hotmail.com
None


In [14]:
for nombre,correo in x.items():
    print(nombre)

Sandra Martinez
Julio Diaz
Ana Dominguez


# Funciones

Como vimos python asigna el tipo de dato a cada variable,dependiendo de la información que contega:

In [15]:
def funcion(x,y):
    return x+y

In [16]:
funcion(4,5.5)

9.5

In [17]:
a=funcion("Esta ", "es una cadena" )

In [18]:
type(a)

str

Nos permite definir argumentos predeterminados, pero estos deben ir después de los argumentos no predeterminados

In [19]:
def funcion2(x,y=5): #sería un error escribir def funcion2(y=5,x)
    return a+b

Si tenemos una función con varios argumentos, al momento de llamar la función nos pedirá que ingresemos como mínimo todos los argumentos no predeterminados. Los argumentos se irán igualando de acuerdo al orden en que están definidos en la función

In [20]:
def funcion3(x,y,t=4,w=5):
    return (x-y)*t-w

In [21]:
print(funcion3(1,2))
print(funcion3(1,2,3))

-9
-8


También podemos ingresar los argumentos en desorden pero debemos llamarlos con los nombres definidos en la función y además deben estar todos los argumentos no predeterminados

In [22]:
funcion3(w=2,y=1,x=10)

34

## Función Lambda

Las funciones lambda son funciones anónimas (sin nombre) y de creación rápida. Pueden tomar cualquier número de argumentos, pero contienen solo una expresión

In [23]:
b=lambda x,y:x+y

In [24]:
b(4,5)

9

# Algunos comentarios sobre Numpy

Esto es adicional a lo ya tratado la semana pasada sobre Numpy

## 1. Tipo de resultado

El tipo del resultado es el mismo que el del array trabajado

In [25]:
import numpy as np

In [26]:
a=np.sqrt(np.arange(-3,1))
a

C:\Users\Sistema\Anaconda3\envs\Ambiente\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([nan, nan, nan,  0.])

In [27]:
a=np.sqrt(np.arange(-3,1).astype(complex))
a

array([0.+1.73205081j, 0.+1.41421356j, 0.+1.j        , 0.+0.j        ])

## 2. Comparación de puntos flotantes

Sabemos que los números de punto flotante no pueden representar con exactitud operaciones como 1/3 o los siguientes ejemplos:

In [28]:
import math
math.sqrt(10)

3.1622776601683795

In [29]:
math.sqrt(10) ** 2

10.000000000000002

Y esto nos puede ocasionar bastantes problemas al momento de ejecutar algunos algoritmos. Por lo cual comparar puntos flotantes con >, < o = no siempre es la mejor opción. Por lo cual Numpy nos ofrece las funciones isclose y allclose para comparar puntos flotantes

## 3. Comportamiento de matrices

En la clase anterior al realizar el código uno de los grupos tuvo un comportamiento similar al siguiente

In [30]:
import numpy as np

In [31]:
r=np.arange(36)
r.resize(6,6)
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [32]:
r2=r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [33]:
r2[:,:]=0 #esto es igual a r2[:,:]=np.zeros([3,3])
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [34]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

El cambio en r2 afecta al comportamiento en r.
<br>Este comportamiento es distinto a otros programas a los que posiblemente estemos acostumbrados, por ejemplo en matlab:
<pre>x=reshape(0:35,6,6).'
x2=x(1:3,1:3)
x2=zeros(3)
x</pre>
Por lo cual __debemos tener en cuenta el comportamiento de las matrices Numpy.__

Si deseamos crear una copia de la matriz r que no cambiará la matriz original, podemos usar copy

In [35]:
r3=r[:4,:4].copy()
r3

array([[ 0,  0,  0,  3],
       [ 0,  0,  0,  9],
       [ 0,  0,  0, 15],
       [18, 19, 20, 21]])

In [36]:
r3[:,:]=1
r3

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [37]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [38]:
r=np.arange(36)
r.resize(6,6)
r=r.T
r

array([[ 0,  6, 12, 18, 24, 30],
       [ 1,  7, 13, 19, 25, 31],
       [ 2,  8, 14, 20, 26, 32],
       [ 3,  9, 15, 21, 27, 33],
       [ 4, 10, 16, 22, 28, 34],
       [ 5, 11, 17, 23, 29, 35]])

<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />Este trabajo elaborado por Jesus J. Baldeon Garcia se distribuye bajo una licencia <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.